services:
  # You need to update this for your plugin name / location
  lint:
    image: buildkite/plugin-linter
    command: [ '--id', 'theopenlane/gcs-rsync' ]
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin"
