name: gcs-rsync
description: Sync a local directory to a Google Cloud Storage bucket using gsutil
author: https://github.com/theopenlane
requirements:
  - bash
configuration:
  properties:
    bucket:
      type: string
      description: The name of the GCS bucket to sync to
    source:
      type: string
      description: The local directory to sync
    project:
      type: string
      description: The GCP project ID
    project-number:
      type: string
      description: The numeric GCP project number
    pool-id:
      type: string
      description: Workload identity pool ID
    service-account:
      type: string
      description: Service account email used for authentication
  required:
    - bucket
    - project
    - project-number
    - pool-id
    - service-account
  additionalProperties: false
