name: gcs-rsync
description: Sync a local directory to a Google Cloud Storage bucket using gsutil
author: https://github.com/theopenlane
requirements:
  - bash
configuration:
  properties:
    bucket:
      type: string
      description: The name of the GCS bucket to sync to
    source:
      type: string
      description: The local directory to sync
    project:
      type: string
      description: The GCP project ID
    service-account-key:
      type: string
      description: The path to the service account key file
  required:
    - bucket
    - project
    - service-account-key
  additionalProperties: false
